<?php 
/*
** User Settings Admin Menu
*/
function ocv_user_settings() {
?>
<div class="ocv_title"><img src="<?php echo ( OCV_PLUGIN_IMAGES_DIR .'one_click_videos.png' );?>" style="width:25%;">
<p class="ocv_title_text">© 2015 <a href="http://codecanyon.net/user/ropstam">Ropstam BPO</a><br />One Click Solution to Publish Videos as Wordpress Post</p></div>
<div id="ocv_user-tabs">
  <ul>
   <li><a href="#ocv_main_settings"><i class="ocv_icon fa fa-cogs"></i><br><strong>Theme Settings</strong></a></li>
    <li><a href="#ocv_dm_wrap_user"><i class="ocv_icon fa fa-video-camera"></i><br><strong>DailyMotion Settings</strong></a></li>
    <li><a href="#ocv_yt_wrap_user"><i class="ocv_icon fa fa-youtube-square"></i><br><strong>Youtube Settings</strong></a></li>
    <li><a href="#ocv_vm_wrap_user"><i class="ocv_icon fa fa-vimeo-square"></i><br><strong>Vimeo Settings</strong></a></li>
  </ul>
<div id="ocv_main_settings">
	<h2>Theme Settings</h2>
	<form method="post" action="options.php">
		<?php settings_fields( 'ocv_settings-user' ); ?>
		<?php do_settings_sections( 'ocv_settings-user' ); ?>
		<table class="form-table">
			<tr valign="top">
			<th scope="row">Video Embed Custom Field</th>
			<td><input type="text" name="ocv_custom_field_video_embed" value="<?php echo esc_attr( get_option( 'ocv_custom_field_video_embed' ) ); ?>" />
			<p>If you want to embed your videos within the post content, simply leave this field empty.<br />
			However, if your theme has a separate custom field for video embeds, please put the custom field ID here.</p></td>
			</tr>
			<tr valign="top">
			<th scope="row">Prefix Video Title.</th>
			<td><input type="text" name="ocv_video_post_title" value="<?php echo esc_attr( get_option( 'ocv_video_post_title' ) ); ?>" />
			<p>Do you want to add something before your Video Post Title ( for example: Must Watch or Exclusive or Breaking ) ? <br/>
			If so, please add that word in the field above and it will be added before your Post Title. <br />
			Leave this field empty if you don't want anything added to videos post title.</p></td>
			</tr>
			<tr valign="top">
			<th scope="row">Add your Content after Video Description.</th>
			<td><textarea rows="5" column="50" name="ocv_video_post_description"><?php echo esc_attr( get_option( 'ocv_video_post_description' ) ); ?></textarea>
			<p>Do you want to add some Text or Content after your Video's Description?  <br/>
			If so, please add that text in the field above and it will be added after your Post Description. <br />
			Leave this field empty if you don't want anything added to videos post Description.</p></td>
			</tr>			
			<?php $ocv_video_post_status = get_option( 'ocv_video_post_status' ); ?>
			<tr valign="top">
			<th scope="row">Post Status</th>
			<td><input type="radio" name="ocv_video_post_status" value="publish" <?php checked( 'publish', $ocv_video_post_status ); ?> />Publish
			<input type="radio" name="ocv_video_post_status" value="draft" <?php checked( 'draft', $ocv_video_post_status ); ?> />Draft
			</td>
			</tr>
			<?php $ocv_video_post_format = get_option( 'ocv_video_post_format' ); ?>
			<tr valign="top">
			<th scope="row">Post Format</th>
			<td><input type="radio" name="ocv_video_post_format" value="standard" <?php checked( 'standard', $ocv_video_post_format ); ?> />Standard
			<input type="radio" name="ocv_video_post_format" value="video" <?php checked( 'video', $ocv_video_post_format ); ?> />Video
			</td>
			</tr>
		</table>
		<?php submit_button(); ?>
	</form>
</div>  
<div id="ocv_dm_wrap_user">
	<h2>DailyMotion User Settings</h2>
	<form method="post" action="options.php">
		<?php settings_fields( 'ocv_settings-dm' ); ?>
		<?php do_settings_sections( 'ocv_settings-dm' ); ?>
		<table class="form-table">
			<tr valign="top">
			<th scope="row">Syndication Key</th>
			<td><input type="text" name="ocv_syndication_key" value="<?php echo esc_attr( get_option( 'ocv_syndication_key' ) ); ?>" />
			<p>Your syndication key is a unique id which will allow Dailymotion to track the revenue generated by the video / widgets you are embedding. <br />
			If you are not earning money from Dailymotion Videos you should signup as <a href="http://publisher.dailymotion.com" target="_blank">DailyMotion Publisher</a></p></td>
			</tr>
			<tr valign="top">
			<th scope="row">Video Player Size</th>
			<td>
			<?php $ocv_size = get_option( 'ocv_size' ); ?>
			<select name="ocv_size" id="youtube_size">
			<option name="ocv_size" value="">Select a Size</option>
			<option name="ocv_size" <?php if ( "width=560 height=315" == $ocv_size ) { echo 'selected="selected"'; } ?> value="width=560 height=315">560 × 315</option>
			<option name="ocv_size" <?php if ( "width=640 height=360" == $ocv_size ) { echo 'selected="selected"'; } ?> value="width=640 height=360">640 × 360</option>
			<option name="ocv_size"<?php if ( "width=853 height=480" == $ocv_size ) { echo 'selected="selected"'; } ?>  value="width=853 height=480">853 × 480</option>
			<option name="ocv_size"<?php if ( "width=1280 height=720" == $ocv_size ) { echo 'selected="selected"'; } ?>  value="width=1280 height=720">1280 × 720</option>
			</select>
			</td>
			</tr>
			<?php $ocv_video_autoplay = get_option('ocv_video_autoplay'); ?>	
			<tr valign="top">
			<th scope="row">AutoPlay Video</th>
			<td><input type="radio" name="ocv_video_autoplay" value="1" <?php checked( '1', $ocv_video_autoplay ); ?> />Yes
			<input type="radio" name="ocv_video_autoplay" value="0" <?php checked( '0', $ocv_video_autoplay ); ?> />No
			</td>
			</tr>
			<tr valign="top">
			<th scope="row">Show related videos when the video finishes</th>
			<?php $ocv_related = get_option( 'ocv_related' ); ?>	
			<td><input type="radio" name="ocv_related" value="1" <?php checked( '1', $ocv_related ); ?> />Yes
			<input type="radio" name="ocv_related" value="0" <?php checked( '0', $ocv_related ); ?> />No
			</td>
			</tr>	
			<tr valign="top">
			<th scope="row">Show player controls</th>
			<?php $ocv_controls = get_option( 'ocv_controls' ); ?>	
			<td><input type="radio" name="ocv_controls" value="1" <?php checked( '1', $ocv_controls ); ?> />Yes
			<input type="radio" name="ocv_controls" value="0" <?php checked( '0', $ocv_controls ); ?> />No
			</td>
			</tr>	
			<tr valign="top">
			<th scope="row">Show video title and player actions</th>
			<?php $ocv_showinfo = get_option( 'ocv_showinfo' ); ?>	
			<td><input type="radio" name="ocv_showinfo" value="1" <?php checked( '1', $ocv_showinfo ); ?> />Yes
			<input type="radio" name="ocv_showinfo" value="0" <?php checked( '0', $ocv_showinfo ); ?> />No
			</td>
			</tr>	
			<tr valign="top">
			<th scope="row">Family Filter</th>
			<?php $ocv_familyfilter = get_option( 'ocv_familyfilter' ); ?>	
			<td><input type="radio" name="ocv_familyfilter" value="true" <?php checked( 'true', $ocv_familyfilter ); ?> />Safe Videos Only
			<input type="radio" name="ocv_familyfilter" value="false" <?php checked( 'false', $ocv_familyfilter ); ?> />Age Restricted Content
			</td>
			</tr>	
		</table>
		<?php submit_button(); ?>
	</form>
</div>
<div id="ocv_yt_wrap_user">
	<h2>Youtube User Settings</h2>
	<form method="post" action="options.php">
		<?php settings_fields( 'ocv_settings-yt' ); ?>
		<?php do_settings_sections( 'ocv_settings-yt' ); ?>
		<table class="form-table">
			<tr valign="top">
			<?php $youtube_public_key = get_option( 'youtube_public_key' ); ?>
			<th scope="row">Youtube Public API Key</th>
			<td><input type="text" name="youtube_public_key" value="<?php echo $youtube_public_key; ?>" />
			<p>Register a FREE youtube developer app by clicking here <a href="https://developers.google.com/youtube/android/player/register">Register APP</a> <br />
			Obtain your Youtube Public API Key <a href="https://developers.google.com/youtube/registering_an_application#Create_API_Keys" target="_blank">Obtain API Key</a></p></td>
			</tr>
			<tr valign="top">
			<th scope="row">Video Player Size</th>
			<td>
			<?php $youtube_size = get_option('youtube_size'); ?>
			<select name="youtube_size" id="youtube_size">
			<option name="youtube_size" value="">Select a Size</option>
			<option name="youtube_size" <?php if ( "width=560 height=315" == $youtube_size ) { echo 'selected="selected"'; } ?> value="width=560 height=315">560 × 315</option>
			<option name="youtube_size" <?php if ( "width=640 height=360" == $youtube_size ) { echo 'selected="selected"'; } ?> value="width=640 height=360">640 × 360</option>
			<option name="youtube_size"<?php if ( "width=853 height=480" == $youtube_size ) { echo 'selected="selected"'; } ?>  value="width=853 height=480">853 × 480</option>
			<option name="youtube_size"<?php if ( "width=1280 height=720" == $youtube_size ) { echo 'selected="selected"'; } ?>  value="width=1280 height=720">1280 × 720</option>
			</select>
			</td>
			</tr>
			<tr valign="top">
			<th scope="row">AutoPlay Video</th>
			<?php $youtube_autoplay = get_option( 'youtube_autoplay' ); ?>	
			<td><input type="radio" name="youtube_autoplay" value="1" <?php checked( '1', $youtube_autoplay ); ?> />Yes
			<input type="radio" name="youtube_autoplay" value="0" <?php checked( '0', $youtube_autoplay ); ?> />No
			</td>
			</tr>
			<tr valign="top">
			<th scope="row">Show related videos when the video finishes</th>
			<?php $youtube_related = get_option( 'youtube_related' ); ?>	
			<td><input type="radio" name="youtube_related" value="1" <?php checked( '1', $youtube_related ); ?> />Yes
			<input type="radio" name="youtube_related" value="0" <?php checked( '0', $youtube_related ); ?> />No
			</td>
			</tr>	
			<tr valign="top">
			<th scope="row">Show player controls</th>
			<?php $youtube_controls = get_option( 'youtube_controls' ); ?>	
			<td><input type="radio" name="youtube_controls" value="1" <?php checked( '1', $youtube_controls ); ?> />Yes
			<input type="radio" name="youtube_controls" value="0" <?php checked( '0', $youtube_controls ); ?> />No
			</td>
			</tr>	
			<tr valign="top">
			<th scope="row">Show video title and player actions</th>
			<?php $youtube_showinfo = get_option( 'youtube_showinfo' ); ?>	
			<td><input type="radio" name="youtube_showinfo" value="1" <?php checked( '1', $youtube_showinfo ); ?> />Yes
			<input type="radio" name="youtube_showinfo" value="0" <?php checked( '0', $youtube_showinfo ); ?> />No
			</td>
			</tr>				
		</table>
		<?php submit_button(); ?>
	</form>
</div>
<div id="ocv_vm_wrap_user">
	<h2>Vimeo User Settings</h2>
	<form method="post" action="options.php">
		<?php settings_fields( 'ocv_settings-vm' ); ?>
		<?php do_settings_sections( 'ocv_settings-vm' ); ?>
		<table class="form-table">
			<tr valign="top">
			<?php $vimeo_client_id = get_option( 'vimeo_client_id' ); ?>
			<th scope="row">VIMEO Client ID</th>
			<td><input type="text" name="vimeo_client_id" value="<?php echo $vimeo_client_id; ?>" />
			</td>
			</tr>
			<tr valign="top">
			<?php $vimeo_client_secret = get_option( 'vimeo_client_secret' ); ?>
			<th scope="row">VIMEO Client Secret</th>
			<td><input type="text" name="vimeo_client_secret" value="<?php echo $vimeo_client_secret; ?>" />
			</td>
			</tr>
			<tr valign="top">
			<th scope="row">Video Player Size</th>
			<td>
			<?php $vimeo_size = get_option( 'vimeo_size' ); ?>
			<select name="vimeo_size" id="youtube_size">
			<option name="vimeo_size" value="">Select a Size</option>
			<option name="vimeo_size" <?php if ( "width=560 height=315" == $vimeo_size ) { echo 'selected="selected"'; } ?> value="width=560 height=315">560 × 315</option>
			<option name="vimeo_size" <?php if ( "width=640 height=360" == $vimeo_size ) { echo 'selected="selected"'; } ?> value="width=640 height=360">640 × 360</option>
			<option name="vimeo_size"<?php if ( "width=853 height=480" == $vimeo_size ) { echo 'selected="selected"'; } ?>  value="width=853 height=480">853 × 480</option>
			<option name="vimeo_size"<?php if ( "width=1280 height=720" == $vimeo_size ) { echo 'selected="selected"'; } ?>  value="width=1280 height=720">1280 × 720</option>
			</select>
			</td>
			</tr>
			<?php $vimeo_autoplay = get_option( 'vimeo_autoplay' ); ?>	
			<tr valign="top">
			<th scope="row">AutoPlay Video</th>
			<td><input type="radio" name="vimeo_autoplay" value="1" <?php checked( '1', $vimeo_autoplay ); ?> />Yes
			<input type="radio" name="vimeo_autoplay" value="0" <?php checked( '0', $vimeo_autoplay ); ?> />No
			</td>
			</tr>
		</table>
		<?php submit_button(); ?>
	</form>
</div>
<?php 
ocv_info_html();
}

function ocv_info_html(){
?>
	<div id="ocv_footer_section">

		<a href="http://codecanyon.net/item/one-click-videos-for-wordpress/12645824"><img src="<?php echo ( OCV_PLUGIN_IMAGES_DIR .'ocv_logo.png' );?>" style="width:100%;"></a>
		<br/><br/>
		<strong>
		DailyMotion Search & Publish Videos PLUGIN ( One Click Videos )is developed by <a href="http://www.walihassan.com" target="_blank">Wali Hassan Jafferi</a> and distributed FREE. </br><br/>
		</strong>
		<strong>Requests: </strong> Please <a href="mailto:walihassanjafferi@gmail.com?Subject=DSP%20Plugin%20Request" target="_top">Email Me</a> for any add-on features. <br/><br/>
		<strong>Feedback: </strong>Please visit <a href="http://www.walihassan.com/dailymotion-search-and-publish-videos-wordpress-plugin/" target="_blank">Comments Section</a> and leave your comments. <br/><br/>
		<strong>Support: </strong>Please create a ticket at <a href="https://wordpress.org/support/plugin/dailymotion-search-and-publish-videos" target="_blank">Wordpress Support Forum</a> and dont forget to leave review & ratings.<br/><br/>
		<strong>Unlock the Full Power | Get Premium Plugin to enable Youtube & Vimeo and lot more</strong>
		<a href="http://codecanyon.net/item/one-click-videos-for-wordpress/12645824"><img src="<?php echo ( OCV_PLUGIN_IMAGES_DIR .'buy.png' );?>" width="75%"></a>
	</div>
<?php
}